### ISSUE TITLE
Sometimes Notepad++ freezes on startup with this plugin

### ISSUE THREAD

**Issue by ItsProfessional** [Zukaritasu/notepadpp_rpc#5]
When I open notepad++, there is about a 30% chance that notepad++ will freeze (not respond). I'm sure that this plugin is the cause, as it does not happen without this plugin.

I'm using Windows 10 22H2 64-bit
Notepad++ v8.4.8 (64-bit)
DiscordRPC version 1.5.389.1

**Comment by Zukaritasu** [comment]
You are right, in version 1.5 this problem was present but in version 1.6 it was solved. To update the plugin to the last version you must delete the DiscordRPC folder located in the path "C:\Program Files\Notepad++\plugins\DiscordRPC", then you must update Notepad++ to the last version and install the plugin from plugin admin. If you have doubts or need more details you can join our discord server https://discord.gg/JTSVh8chcx and leave your comment in the #npp-support channel.
